/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import React, { useState, useRef, useEffect } from 'react';
import { 
  Code2, 
  Copy, 
  Download, 
  Settings, 
  Box, 
  Cpu, 
  Layers, 
  Check,
  Terminal,
  FileCode,
  Info,
  MessageSquare,
  Send,
  Sparkles,
  Loader2,
  ChevronRight,
  ChevronLeft,
  RotateCcw
} from 'lucide-react';
import { motion, AnimatePresence } from 'motion/react';
import { GoogleGenAI } from "@google/genai";

type PluginType = 'CommandData' | 'ObjectData' | 'TagData' | 'ToolData';

interface PluginConfig {
  name: string;
  id: string;
  type: PluginType;
  description: string;
}

interface Message {
  role: 'user' | 'model';
  text: string;
}

const SYSTEM_INSTRUCTION = `You are an expert Cinema 4D Python SDK developer. 
Your goal is to help users write high-quality Python plugins for Cinema 4D 2024.
Cinema 4D 2024 uses Python 3.11.
When the user asks for a specific feature or modification, provide the FULL code for a .pyp file.
Wrap your Python code in triple backticks with the language specified (e.g., \`\`\`python ... \`\`\`).
The code you provide will be automatically extracted and displayed in the main code editor area.
Focus on standard classes like CommandData, ObjectData, TagData, and ToolData.
Be concise and technical.`;

export default function App() {
  const [config, setConfig] = useState<PluginConfig>({
    name: 'MyAwesomePlugin',
    id: '1000001',
    type: 'CommandData',
    description: 'A custom plugin for Cinema 4D 2024'
  });

  const [copied, setCopied] = useState(false);
  const [isChatOpen, setIsChatOpen] = useState(true);
  const [messages, setMessages] = useState<Message[]>([
    { role: 'model', text: 'Hello! I am your C4D AI Architect. Describe the feature you want, and I will write the code directly into the editor for you.' }
  ]);
  const [input, setInput] = useState('');
  const [isLoading, setIsLoading] = useState(false);
  const [customCode, setCustomCode] = useState<string | null>(null);
  const chatEndRef = useRef<HTMLDivElement>(null);

  const scrollToBottom = () => {
    chatEndRef.current?.scrollIntoView({ behavior: "smooth" });
  };

  useEffect(() => {
    scrollToBottom();
  }, [messages]);

  const extractCode = (text: string) => {
    const regex = /```(?:python)?\s*([\s\S]*?)```/i;
    const match = text.match(regex);
    return match ? match[1].trim() : null;
  };

  const handleSendMessage = async () => {
    if (!input.trim() || isLoading) return;

    const userMessage: Message = { role: 'user', text: input };
    setMessages(prev => [...prev, userMessage]);
    setInput('');
    setIsLoading(true);

    try {
      const ai = new GoogleGenAI({ apiKey: process.env.GEMINI_API_KEY });
      const response = await ai.models.generateContent({
        model: "gemini-3.1-pro-preview",
        contents: messages.concat(userMessage).map(m => ({
          role: m.role,
          parts: [{ text: m.text }]
        })),
        config: {
          systemInstruction: SYSTEM_INSTRUCTION,
        }
      });

      const modelText = response.text || "I'm sorry, I couldn't generate a response.";
      
      // Extract code and update editor
      const code = extractCode(modelText);
      if (code) {
        setCustomCode(code);
        setMessages(prev => [...prev, { role: 'model', text: "I've updated the code editor with the requested implementation. You can see it in the main area." }]);
      } else {
        setMessages(prev => [...prev, { role: 'model', text: modelText }]);
      }
    } catch (error) {
      console.error("AI Error:", error);
      setMessages(prev => [...prev, { role: 'model', text: "Error: Failed to connect to the AI architect. Please check your connection." }]);
    } finally {
      setIsLoading(false);
    }
  };

  const generateBoilerplate = () => {
    const { name, id, type, description } = config;
    
    const header = `"""
${name}
Cinema 4D 2024 Python Plugin
Generated by C4D Plugin Architect
"""

import c4d
import os

# Unique Plugin ID (Get one from developers.maxon.net)
PLUGIN_ID = ${id}
`;

    if (type === 'CommandData') {
      return `${header}
class ${name}Command(c4d.plugins.CommandData):
    """
    A CommandData plugin that appears in the Extensions menu.
    """
    
    def Execute(self, doc):
        """
        Called when the user clicks the menu item.
        """
        c4d.gui.MessageDialog("Hello from ${name}!")
        return True

    def GetState(self, doc):
        """
        Controls if the menu item is enabled or checked.
        """
        return c4d.CMD_ENABLED

if __name__ == "__main__":
    # Register the plugin
    icon = None # Add a c4d.bitmaps.BaseBitmap() here if needed
    
    result = c4d.plugins.RegisterCommandPlugin(
        id=PLUGIN_ID,
        str="${name}",
        info=0,
        icon=icon,
        help="${description}",
        dat=${name}Command()
    )
    
    if result:
        print(f"Successfully registered ${name}")
    else:
        print(f"Failed to register ${name}")
`;
    }

    if (type === 'ObjectData') {
      return `${header}
class ${name}Object(c4d.plugins.ObjectData):
    """
    An ObjectData plugin for creating custom geometry or generators.
    """
    
    def __init__(self):
        self.SetOptimizeCache(True)

    def GetVirtualObjects(self, op, hierarchyhelp):
        """
        Returns the geometry cache for the object.
        """
        # Create a simple cube as a placeholder
        cube = c4d.BaseObject(c4d.Ocube)
        if cube is None:
            return None
            
        return cube

if __name__ == "__main__":
    # Register the plugin
    result = c4d.plugins.RegisterObjectPlugin(
        id=PLUGIN_ID,
        str="${name}",
        g=${name}Object,
        description="O${name.toLowerCase()}", # Resource file name
        icon=None,
        info=c4d.OBJECT_GENERATOR
    )
    
    if result:
        print(f"Successfully registered ${name} Object")
`;
    }

    return "# Plugin type template coming soon...";
  };

  const currentCode = customCode || generateBoilerplate();

  const handleCopy = () => {
    navigator.clipboard.writeText(currentCode);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const handleReset = () => {
    setCustomCode(null);
    setMessages(prev => [...prev, { role: 'model', text: "Reset to standard boilerplate." }]);
  };

  return (
    <div className="min-h-screen bg-blueprint-bg text-blueprint-text font-sans selection:bg-blueprint-accent selection:text-blueprint-bg flex flex-col">
      {/* Header Grid */}
      <header className="border-b border-blueprint-accent/30 p-6 flex justify-between items-center bg-blueprint-panel/80 backdrop-blur-md sticky top-0 z-50">
        <div className="flex items-center gap-3">
          <div className="p-2 bg-blueprint-accent text-blueprint-bg rounded-sm shadow-[0_0_15px_rgba(0,210,255,0.3)]">
            <Cpu size={24} />
          </div>
          <div>
            <h1 className="text-xl font-bold tracking-tighter uppercase font-display text-blueprint-accent">C4D Plugin Architect</h1>
            <p className="text-[10px] uppercase tracking-[0.2em] opacity-50 font-mono">Cinema 4D 2024 SDK Boilerplate</p>
          </div>
        </div>
        <div className="flex gap-4">
          <button 
            onClick={() => setIsChatOpen(!isChatOpen)}
            className={`flex items-center gap-2 px-4 py-2 border border-blueprint-accent transition-all text-xs uppercase font-bold tracking-widest ${isChatOpen ? 'bg-blueprint-accent text-blueprint-bg shadow-[0_0_10px_rgba(0,210,255,0.4)]' : 'hover:bg-blueprint-accent hover:text-blueprint-bg'}`}
          >
            <Sparkles size={14} />
            AI Architect
          </button>
          <button 
            onClick={handleCopy}
            className="flex items-center gap-2 px-4 py-2 border border-blueprint-accent hover:bg-blueprint-accent hover:text-blueprint-bg transition-all text-xs uppercase font-bold tracking-widest"
          >
            {copied ? <Check size={14} /> : <Copy size={14} />}
            {copied ? 'Copied' : 'Copy Code'}
          </button>
        </div>
      </header>

      <main className="flex-1 grid grid-cols-1 lg:grid-cols-[400px_1fr_auto] overflow-hidden">
        {/* Sidebar Controls */}
        <section className="border-r border-blueprint-accent/20 p-8 space-y-8 bg-blueprint-panel/40 overflow-y-auto backdrop-blur-sm">
          <div className="space-y-6">
            <div className="flex items-center gap-2 opacity-50">
              <Settings size={14} className="text-blueprint-accent" />
              <span className="text-[10px] uppercase font-bold tracking-widest">Configuration</span>
            </div>

            <div className="space-y-4">
              <div className="space-y-1">
                <label className="text-[11px] font-display font-medium opacity-60 uppercase tracking-wider text-blueprint-accent">Plugin Name</label>
                <input 
                  type="text"
                  value={config.name}
                  onChange={(e) => setConfig({ ...config, name: e.target.value })}
                  className="w-full bg-transparent border-b border-blueprint-accent/40 py-2 focus:outline-none font-mono text-sm focus:border-blueprint-accent transition-colors"
                />
              </div>

              <div className="space-y-1">
                <label className="text-[11px] font-display font-medium opacity-60 uppercase tracking-wider text-blueprint-accent">Plugin ID</label>
                <input 
                  type="text"
                  value={config.id}
                  onChange={(e) => setConfig({ ...config, id: e.target.value })}
                  className="w-full bg-transparent border-b border-blueprint-accent/40 py-2 focus:outline-none font-mono text-sm focus:border-blueprint-accent transition-colors"
                />
                <p className="text-[9px] opacity-40 mt-1">Get a unique ID from developers.maxon.net</p>
              </div>

              <div className="space-y-1">
                <label className="text-[11px] font-display font-medium opacity-60 uppercase tracking-wider text-blueprint-accent">Plugin Type</label>
                <div className="grid grid-cols-2 gap-2 pt-2">
                  {(['CommandData', 'ObjectData'] as PluginType[]).map((type) => (
                    <button
                      key={type}
                      onClick={() => {
                        setConfig({ ...config, type });
                        setCustomCode(null); // Reset custom code when switching types
                      }}
                      className={`px-3 py-2 text-[10px] font-bold uppercase tracking-wider border transition-all ${
                        config.type === type 
                        ? 'bg-blueprint-accent text-blueprint-bg border-blueprint-accent' 
                        : 'border-blueprint-accent/20 hover:border-blueprint-accent/60'
                      }`}
                    >
                      {type}
                    </button>
                  ))}
                </div>
              </div>

              <div className="space-y-1">
                <label className="text-[11px] font-display font-medium opacity-60 uppercase tracking-wider text-blueprint-accent">Description</label>
                <textarea 
                  value={config.description}
                  onChange={(e) => setConfig({ ...config, description: e.target.value })}
                  className="w-full bg-transparent border border-blueprint-accent/20 p-3 focus:outline-none font-mono text-xs h-24 focus:border-blueprint-accent transition-colors"
                />
              </div>
            </div>
          </div>

          <div className="p-4 border border-dashed border-blueprint-accent/30 rounded-sm bg-blueprint-accent/5 space-y-3">
            <div className="flex items-center gap-2">
              <Info size={14} className="opacity-50 text-blueprint-accent" />
              <span className="text-[10px] font-bold uppercase tracking-widest">SDK Notes</span>
            </div>
            <p className="text-[11px] leading-relaxed opacity-70">
              Cinema 4D 2024 uses Python 3.11. Ensure your environment matches. 
              Place the generated <code className="font-mono bg-blueprint-accent/10 px-1 text-blueprint-accent">.pyp</code> file in your plugins directory.
            </p>
          </div>
        </section>

        {/* Code Preview Area */}
        <section className="bg-blueprint-code text-blueprint-text/80 p-0 flex flex-col overflow-hidden">
          <div className="flex items-center justify-between px-6 py-3 border-b border-blueprint-accent/10 bg-blueprint-panel/60">
            <div className="flex items-center gap-3">
              <FileCode size={14} className="text-blueprint-accent" />
              <span className="text-[10px] font-mono tracking-wider uppercase opacity-50">
                {config.name.toLowerCase()}.pyp {customCode && <span className="text-yellow-400 ml-2">(AI MODIFIED)</span>}
              </span>
            </div>
            <div className="flex items-center gap-4">
              {customCode && (
                <button 
                  onClick={handleReset}
                  className="flex items-center gap-1 text-[9px] uppercase font-bold tracking-widest text-red-400 hover:text-red-300 transition-colors"
                >
                  <RotateCcw size={12} />
                  Reset to Boilerplate
                </button>
              )}
              <div className="flex gap-1">
                <div className="w-2 h-2 rounded-full bg-red-500/50" />
                <div className="w-2 h-2 rounded-full bg-yellow-500/50" />
                <div className="w-2 h-2 rounded-full bg-green-500/50" />
              </div>
            </div>
          </div>
          
          <div className="flex-1 overflow-auto p-8 font-mono text-sm leading-relaxed custom-scrollbar">
            <pre className="whitespace-pre-wrap">
              {currentCode.split('\n').map((line, i) => (
                <div key={i} className="flex gap-6 group">
                  <span className="w-8 text-right opacity-20 select-none group-hover:opacity-40 transition-opacity">
                    {i + 1}
                  </span>
                  <span className={
                    line.trim().startsWith('#') || line.trim().startsWith('"""') 
                    ? 'text-green-400/70 italic' 
                    : line.includes('class') || line.includes('def') || line.includes('import')
                    ? 'text-blueprint-accent'
                    : line.includes('c4d')
                    ? 'text-cyan-300'
                    : 'text-blueprint-text/90'
                  }>
                    {line}
                  </span>
                </div>
              ))}
            </pre>
          </div>
        </section>

        {/* AI Architect Panel */}
        <AnimatePresence>
          {isChatOpen && (
            <motion.section 
              initial={{ width: 0, opacity: 0 }}
              animate={{ width: 450, opacity: 1 }}
              exit={{ width: 0, opacity: 0 }}
              className="border-l border-blueprint-accent/20 bg-blueprint-panel flex flex-col overflow-hidden relative shadow-2xl"
            >
              <div className="p-6 border-b border-blueprint-accent/30 flex items-center justify-between bg-blueprint-accent text-blueprint-bg">
                <div className="flex items-center gap-3">
                  <Sparkles size={18} />
                  <h2 className="text-sm font-bold uppercase tracking-widest">AI Architect</h2>
                </div>
                <button 
                  onClick={() => setIsChatOpen(false)}
                  className="p-1 hover:bg-white/10 rounded-sm transition-colors"
                >
                  <ChevronRight size={20} />
                </button>
              </div>

              <div className="flex-1 overflow-y-auto p-6 space-y-6 custom-scrollbar-light">
                {messages.map((msg, i) => (
                  <div key={i} className={`flex flex-col ${msg.role === 'user' ? 'items-end' : 'items-start'}`}>
                    <div className={`max-w-[90%] p-4 rounded-sm text-xs leading-relaxed ${
                      msg.role === 'user' 
                      ? 'bg-blueprint-accent text-blueprint-bg' 
                      : 'bg-blueprint-code text-blueprint-text border border-blueprint-accent/10'
                    }`}>
                      {msg.text.split('\n').map((line, j) => (
                        <p key={j} className={line.startsWith('```') ? 'hidden' : ''}>
                          {line}
                        </p>
                      ))}
                      {msg.role === 'model' && extractCode(msg.text) && (
                        <div className="mt-2 pt-2 border-t border-blueprint-accent/10 flex items-center gap-2 text-[10px] font-bold text-blueprint-accent uppercase">
                          <Check size={12} />
                          Code applied to editor
                        </div>
                      )}
                    </div>
                    <span className="text-[9px] uppercase font-bold tracking-tighter opacity-30 mt-2">
                      {msg.role === 'user' ? 'You' : 'Architect'}
                    </span>
                  </div>
                ))}
                {isLoading && (
                  <div className="flex items-center gap-2 text-blueprint-accent/50">
                    <Loader2 size={14} className="animate-spin" />
                    <span className="text-[10px] font-bold uppercase tracking-widest">Architect is thinking...</span>
                  </div>
                )}
                <div ref={chatEndRef} />
              </div>

              <div className="p-6 border-t border-blueprint-accent/20 bg-blueprint-panel/60">
                <div className="relative flex items-center">
                  <input 
                    type="text"
                    value={input}
                    onChange={(e) => setInput(e.target.value)}
                    onKeyDown={(e) => e.key === 'Enter' && handleSendMessage()}
                    placeholder="Describe a feature (e.g. 'Add a button to rename objects')..."
                    className="w-full bg-blueprint-code border border-blueprint-accent/40 p-4 pr-12 focus:outline-none text-xs font-mono shadow-[4px_4px_0px_0px_rgba(0,210,255,0.3)] focus:shadow-[2px_2px_0px_0px_rgba(0,210,255,0.3)] transition-all text-blueprint-text placeholder:text-blueprint-text/30"
                  />
                  <button 
                    onClick={handleSendMessage}
                    disabled={isLoading}
                    className="absolute right-4 p-2 text-blueprint-accent hover:scale-110 transition-transform disabled:opacity-50"
                  >
                    <Send size={18} />
                  </button>
                </div>
              </div>
            </motion.section>
          )}
        </AnimatePresence>
      </main>

      <style dangerouslySetInnerHTML={{ __html: `
        .custom-scrollbar::-webkit-scrollbar {
          width: 8px;
          height: 8px;
        }
        .custom-scrollbar::-webkit-scrollbar-track {
          background: #050f1d;
        }
        .custom-scrollbar::-webkit-scrollbar-thumb {
          background: #0d2a50;
          border-radius: 4px;
          border: 1px solid rgba(0, 210, 255, 0.1);
        }
        .custom-scrollbar::-webkit-scrollbar-thumb:hover {
          background: #00d2ff22;
        }

        .custom-scrollbar-light::-webkit-scrollbar {
          width: 6px;
        }
        .custom-scrollbar-light::-webkit-scrollbar-track {
          background: transparent;
        }
        .custom-scrollbar-light::-webkit-scrollbar-thumb {
          background: rgba(0, 210, 255, 0.2);
          border-radius: 3px;
        }
        .custom-scrollbar-light::-webkit-scrollbar-thumb:hover {
          background: rgba(0, 210, 255, 0.4);
        }
      `}} />
    </div>
  );
}
