/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import React, { useState, useRef, useEffect } from 'react';
import { 
  Code2, 
  Copy, 
  Download, 
  Settings, 
  Box, 
  Cpu, 
  Layers, 
  Check,
  Terminal,
  FileCode,
  Info,
  MessageSquare,
  Send,
  Sparkles,
  Loader2,
  ChevronRight,
  ChevronLeft,
  RotateCcw
} from 'lucide-react';
import { motion, AnimatePresence } from 'motion/react';
import { GoogleGenAI } from "@google/genai";

type PluginType = 'CommandData' | 'ObjectData' | 'TagData' | 'ToolData';

interface PluginConfig {
  name: string;
  id: string;
  type: PluginType;
  description: string;
}

interface Message {
  role: 'user' | 'model';
  text: string;
}

const SYSTEM_INSTRUCTION = `You are an expert Cinema 4D Python SDK developer. 
Your goal is to help users write high-quality Python plugins for Cinema 4D 2024.
Cinema 4D 2024 uses Python 3.11.
When the user asks for a specific feature or modification, provide the FULL code for a .pyp file.
Wrap your Python code in triple backticks with the language specified (e.g., \`\`\`python ... \`\`\`).
The code you provide will be automatically extracted and displayed in the main code editor area.
Focus on standard classes like CommandData, ObjectData, TagData, and ToolData.
Be concise and technical.`;

export default function App() {
  const [config, setConfig] = useState<PluginConfig>({
    name: 'MyAwesomePlugin',
    id: '1000001',
    type: 'CommandData',
    description: 'A custom plugin for Cinema 4D 2024'
  });

  const [copied, setCopied] = useState(false);
  const [isChatOpen, setIsChatOpen] = useState(true);
  const [messages, setMessages] = useState<Message[]>([
    { role: 'model', text: 'Hello! I am your C4D AI Architect. Describe the feature you want, and I will write the code directly into the editor for you.' }
  ]);
  const [input, setInput] = useState('');
  const [isLoading, setIsLoading] = useState(false);
  const [customCode, setCustomCode] = useState<string | null>(null);
  const chatEndRef = useRef<HTMLDivElement>(null);

  const scrollToBottom = () => {
    chatEndRef.current?.scrollIntoView({ behavior: "smooth" });
  };

  useEffect(() => {
    scrollToBottom();
  }, [messages]);

  const extractCode = (text: string) => {
    const regex = /```(?:python)?\s*([\s\S]*?)```/i;
    const match = text.match(regex);
    return match ? match[1].trim() : null;
  };

  const handleSendMessage = async () => {
    if (!input.trim() || isLoading) return;

    const userMessage: Message = { role: 'user', text: input };
    setMessages(prev => [...prev, userMessage]);
    setInput('');
    setIsLoading(true);

    try {
      const ai = new GoogleGenAI({ apiKey: process.env.GEMINI_API_KEY });
      const response = await ai.models.generateContent({
        model: "gemini-3.1-pro-preview",
        contents: messages.concat(userMessage).map(m => ({
          role: m.role,
          parts: [{ text: m.text }]
        })),
        config: {
          systemInstruction: SYSTEM_INSTRUCTION,
        }
      });

      const modelText = response.text || "I'm sorry, I couldn't generate a response.";
      
      // Extract code and update editor
      const code = extractCode(modelText);
      if (code) {
        setCustomCode(code);
        setMessages(prev => [...prev, { role: 'model', text: "I've updated the code editor with the requested implementation. You can see it in the main area." }]);
      } else {
        setMessages(prev => [...prev, { role: 'model', text: modelText }]);
      }
    } catch (error) {
      console.error("AI Error:", error);
      setMessages(prev => [...prev, { role: 'model', text: "Error: Failed to connect to the AI architect. Please check your connection." }]);
    } finally {
      setIsLoading(false);
    }
  };

  const generateBoilerplate = () => {
    const { name, id, type, description } = config;
    
    const header = `"""
${name}
Cinema 4D 2024 Python Plugin
Generated by C4D Plugin Architect
"""

import c4d
import os

# Unique Plugin ID (Get one from developers.maxon.net)
PLUGIN_ID = ${id}
`;

    if (type === 'CommandData') {
      return `${header}
class ${name}Command(c4d.plugins.CommandData):
    """
    A CommandData plugin that appears in the Extensions menu.
    """
    
    def Execute(self, doc):
        """
        Called when the user clicks the menu item.
        """
        c4d.gui.MessageDialog("Hello from ${name}!")
        return True

    def GetState(self, doc):
        """
        Controls if the menu item is enabled or checked.
        """
        return c4d.CMD_ENABLED

if __name__ == "__main__":
    # Register the plugin
    icon = None # Add a c4d.bitmaps.BaseBitmap() here if needed
    
    result = c4d.plugins.RegisterCommandPlugin(
        id=PLUGIN_ID,
        str="${name}",
        info=0,
        icon=icon,
        help="${description}",
        dat=${name}Command()
    )
    
    if result:
        print(f"Successfully registered ${name}")
    else:
        print(f"Failed to register ${name}")
`;
    }

    if (type === 'ObjectData') {
      return `${header}
class ${name}Object(c4d.plugins.ObjectData):
    """
    An ObjectData plugin for creating custom geometry or generators.
    """
    
    def __init__(self):
        self.SetOptimizeCache(True)

    def GetVirtualObjects(self, op, hierarchyhelp):
        """
        Returns the geometry cache for the object.
        """
        # Create a simple cube as a placeholder
        cube = c4d.BaseObject(c4d.Ocube)
        if cube is None:
            return None
            
        return cube

if __name__ == "__main__":
    # Register the plugin
    result = c4d.plugins.RegisterObjectPlugin(
        id=PLUGIN_ID,
        str="${name}",
        g=${name}Object,
        description="O${name.toLowerCase()}", # Resource file name
        icon=None,
        info=c4d.OBJECT_GENERATOR
    )
    
    if result:
        print(f"Successfully registered ${name} Object")
`;
    }

    return "# Plugin type template coming soon...";
  };

  const currentCode = customCode || generateBoilerplate();

  const handleCopy = () => {
    navigator.clipboard.writeText(currentCode);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const handleReset = () => {
    setCustomCode(null);
    setMessages(prev => [...prev, { role: 'model', text: "Reset to standard boilerplate." }]);
  };

  const handleDownload = () => {
    const blob = new Blob([currentCode], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `${config.name.toLowerCase() || 'plugin'}.pyp`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  return (
    <div className="h-screen bg-blueprint-bg text-blueprint-text font-sans selection:bg-blueprint-accent selection:text-blueprint-bg flex flex-col overflow-hidden">
      {/* Header */}
      <header className="border-b border-blueprint-border p-3 flex justify-between items-center bg-blueprint-panel sticky top-0 z-50">
        <div className="flex items-center gap-3">
          <div className="text-blueprint-accent">
            <Cpu size={20} />
          </div>
          <h1 className="text-sm font-bold tracking-tight uppercase text-blueprint-text">C4D.ARCHITECT</h1>
        </div>
        <div className="flex gap-2">
          <button 
            onClick={() => setIsChatOpen(!isChatOpen)}
            className={`flex items-center gap-2 px-3 py-1.5 rounded transition-all text-[11px] font-semibold uppercase tracking-wide ${isChatOpen ? 'bg-blueprint-accent text-white' : 'bg-blueprint-border/30 text-blueprint-text-muted hover:text-blueprint-text hover:bg-blueprint-border/50'}`}
          >
            <Sparkles size={14} />
            AI Architect
          </button>
          <button 
            onClick={handleCopy}
            className="flex items-center gap-2 px-3 py-1.5 bg-blueprint-border/30 border border-blueprint-border/50 text-blueprint-text rounded hover:bg-blueprint-border/50 transition-all text-[11px] font-semibold uppercase tracking-wide"
          >
            {copied ? <Check size={14} /> : <Copy size={14} />}
            {copied ? 'Copied' : 'Copy Code'}
          </button>
          <button 
            onClick={handleDownload}
            className="flex items-center gap-2 px-3 py-1.5 bg-blueprint-accent text-white border border-blueprint-accent/50 rounded hover:bg-blueprint-accent/90 transition-all text-[11px] font-semibold uppercase tracking-wide"
          >
            <Download size={14} />
            Download .pyp
          </button>
        </div>
      </header>

      <main className="flex-1 grid grid-cols-1 lg:grid-cols-[400px_1fr_auto] overflow-hidden">
        {/* Sidebar Controls */}
        <section className="border-r border-blueprint-border p-5 space-y-8 bg-blueprint-panel overflow-y-auto custom-scrollbar">
          <div className="space-y-6">
            <div className="space-y-5">
              <div className="space-y-1.5">
                <label className="text-[10px] font-bold uppercase tracking-wider text-blueprint-text-muted">Plugin Name</label>
                <input 
                  type="text"
                  value={config.name}
                  onChange={(e) => setConfig({ ...config, name: e.target.value })}
                  className="w-full bg-blueprint-bg border border-blueprint-border rounded px-3 py-2 focus:outline-none font-mono text-xs focus:border-blueprint-accent transition-colors text-blueprint-text"
                />
              </div>

              <div className="space-y-1.5">
                <label className="text-[10px] font-bold uppercase tracking-wider text-blueprint-text-muted">Plugin ID</label>
                <input 
                  type="text"
                  value={config.id}
                  onChange={(e) => setConfig({ ...config, id: e.target.value })}
                  className="w-full bg-blueprint-bg border border-blueprint-border rounded px-3 py-2 focus:outline-none font-mono text-xs focus:border-blueprint-accent transition-colors text-blueprint-text"
                />
              </div>

              <div className="space-y-1.5">
                <label className="text-[10px] font-bold uppercase tracking-wider text-blueprint-text-muted">Plugin Type</label>
                <div className="grid grid-cols-2 gap-2 pt-1">
                  {(['CommandData', 'ObjectData'] as PluginType[]).map((type) => (
                    <button
                      key={type}
                      onClick={() => {
                        setConfig({ ...config, type });
                        setCustomCode(null);
                      }}
                      className={`px-3 py-2 text-[10px] font-bold uppercase tracking-wider border rounded transition-all ${
                        config.type === type 
                        ? 'bg-blueprint-accent text-white border-blueprint-accent' 
                        : 'border-blueprint-border text-blueprint-text-muted hover:border-blueprint-text-muted/50 hover:text-blueprint-text'
                      }`}
                    >
                      {type}
                    </button>
                  ))}
                </div>
              </div>

              <div className="space-y-1.5">
                <label className="text-[10px] font-bold uppercase tracking-wider text-blueprint-text-muted">Description</label>
                <textarea 
                  value={config.description}
                  onChange={(e) => setConfig({ ...config, description: e.target.value })}
                  className="w-full bg-blueprint-bg border border-blueprint-border rounded px-3 py-2 focus:outline-none font-mono text-xs h-24 focus:border-blueprint-accent transition-colors text-blueprint-text resize-none"
                />
              </div>
            </div>
          </div>

          <div className="p-4 border border-blueprint-border rounded bg-blueprint-bg/30 space-y-3">
            <div className="flex items-center gap-2">
              <Info size={14} className="text-blueprint-accent" />
              <span className="text-[10px] font-bold uppercase tracking-widest text-blueprint-text">SDK Notes</span>
            </div>
            <p className="text-[10px] leading-relaxed text-blueprint-text-muted">
              Cinema 4D 2024 uses Python 3.11. Ensure your environment matches. 
              Place the generated <code className="font-mono bg-blueprint-bg px-1 rounded text-blueprint-text">.pyp</code> file in your plugins directory.
            </p>
          </div>
        </section>

        {/* Code Preview Area */}
        <section className="bg-blueprint-bg text-blueprint-text/80 p-0 flex flex-col overflow-hidden">
          <div className="flex items-center justify-between px-6 py-2 border-b border-blueprint-border bg-blueprint-panel/30">
            <div className="flex items-center gap-3">
              <FileCode size={14} className="text-blueprint-accent" />
              <span className="text-[10px] font-mono tracking-wider uppercase text-blueprint-text-muted">
                {config.name.toLowerCase()}.pyp {customCode && <span className="text-yellow-500 ml-2">(AI MODIFIED)</span>}
              </span>
            </div>
            <div className="flex items-center gap-4">
              {customCode && (
                <button 
                  onClick={handleReset}
                  className="flex items-center gap-1 text-[9px] uppercase font-bold tracking-widest text-red-500 hover:text-red-400 transition-colors"
                >
                  <RotateCcw size={12} />
                  Reset
                </button>
              )}
              <div className="flex gap-1.5">
                <div className="w-2.5 h-2.5 rounded-full bg-blueprint-border" />
                <div className="w-2.5 h-2.5 rounded-full bg-blueprint-border" />
                <div className="w-2.5 h-2.5 rounded-full bg-blueprint-border" />
              </div>
            </div>
          </div>
          
          <div className="flex-1 overflow-auto p-8 font-mono text-xs leading-relaxed custom-scrollbar">
            <pre className="whitespace-pre-wrap">
              {currentCode.split('\n').map((line, i) => (
                <div key={i} className="flex gap-6 group">
                  <span className="w-8 text-right text-blueprint-text-muted/20 select-none group-hover:text-blueprint-text-muted/40 transition-colors">
                    {i + 1}
                  </span>
                  <span className={
                    line.trim().startsWith('#') || line.trim().startsWith('"""') 
                    ? 'text-blueprint-text-muted/50 italic' 
                    : line.includes('class') || line.includes('def') || line.includes('import')
                    ? 'text-white font-semibold'
                    : line.includes('c4d')
                    ? 'text-blueprint-accent'
                    : line.includes('"') || line.includes("'")
                    ? 'text-emerald-400/80'
                    : 'text-blueprint-text/80'
                  }>
                    {line}
                  </span>
                </div>
              ))}
            </pre>
          </div>
        </section>

        {/* AI Architect Panel */}
        <AnimatePresence>
          {isChatOpen && (
            <motion.section 
              initial={{ width: 0, opacity: 0 }}
              animate={{ width: 400, opacity: 1 }}
              exit={{ width: 0, opacity: 0 }}
              className="border-l border-blueprint-border bg-blueprint-panel flex flex-col overflow-hidden relative shadow-2xl"
            >
              <div className="p-4 border-b border-blueprint-border flex items-center justify-between bg-blueprint-panel">
                <div className="flex items-center gap-2.5">
                  <Sparkles size={16} className="text-blueprint-accent" />
                  <h2 className="text-[11px] font-bold uppercase tracking-widest text-blueprint-text">PROPERTIES</h2>
                </div>
                <button 
                  onClick={() => setIsChatOpen(false)}
                  className="p-1 hover:bg-white/5 rounded transition-colors text-blueprint-text-muted"
                >
                  <ChevronRight size={18} />
                </button>
              </div>

              <div className="flex-1 overflow-y-auto p-5 space-y-5 custom-scrollbar">
                {messages.map((msg, i) => (
                  <div key={i} className={`flex flex-col ${msg.role === 'user' ? 'items-end' : 'items-start'}`}>
                    <div className={`max-w-[90%] p-3.5 rounded text-[11px] leading-relaxed ${
                      msg.role === 'user' 
                      ? 'bg-blueprint-accent text-white font-medium' 
                      : 'bg-blueprint-bg text-blueprint-text border border-blueprint-border'
                    }`}>
                      {msg.text.split('\n').map((line, j) => (
                        <p key={j} className={line.startsWith('```') ? 'hidden' : 'mb-1 last:mb-0'}>
                          {line}
                        </p>
                      ))}
                      {msg.role === 'model' && extractCode(msg.text) && (
                        <div className="mt-2 pt-2 border-t border-blueprint-border flex items-center gap-2 text-[9px] font-bold text-blueprint-accent uppercase">
                          <Check size={10} />
                          Editor Updated
                        </div>
                      )}
                    </div>
                  </div>
                ))}
                {isLoading && (
                  <div className="flex items-center gap-2 text-blueprint-text-muted/50">
                    <Loader2 size={12} className="animate-spin" />
                    <span className="text-[9px] font-bold uppercase tracking-widest text-blueprint-accent">Thinking...</span>
                  </div>
                )}
                <div ref={chatEndRef} />
              </div>

              <div className="p-5 border-t border-blueprint-border bg-blueprint-panel">
                <div className="relative flex items-center">
                  <input 
                    type="text"
                    value={input}
                    onChange={(e) => setInput(e.target.value)}
                    onKeyDown={(e) => e.key === 'Enter' && handleSendMessage()}
                    placeholder="Ask for a feature..."
                    className="w-full bg-blueprint-bg border border-blueprint-border rounded p-3.5 pr-12 focus:outline-none text-[11px] font-mono transition-all text-blueprint-text placeholder:text-blueprint-text-muted/30"
                  />
                  <button 
                    onClick={handleSendMessage}
                    disabled={isLoading}
                    className="absolute right-3.5 p-1.5 text-blueprint-accent hover:scale-110 transition-transform disabled:opacity-50"
                  >
                    <Send size={16} />
                  </button>
                </div>
              </div>
            </motion.section>
          )}
        </AnimatePresence>
      </main>

      <style dangerouslySetInnerHTML={{ __html: `
        .custom-scrollbar::-webkit-scrollbar {
          width: 8px;
          height: 8px;
        }
        .custom-scrollbar::-webkit-scrollbar-track {
          background: var(--color-blueprint-bg);
        }
        .custom-scrollbar::-webkit-scrollbar-thumb {
          background: var(--color-blueprint-border);
          border-radius: 4px;
        }
        .custom-scrollbar::-webkit-scrollbar-thumb:hover {
          background: var(--color-blueprint-accent);
          opacity: 0.5;
        }
`}} />
    </div>
  );
}
